"""Generate a shared measured-outline loft .scad from a reference tessellation.

The outer form of a body is emitted as `profiles` (per-station X-Z convex section
outlines, ordered CCW, measured by slicing the reference mesh) plus an
`outer_body()` module that lofts them with ruled hulls. Parts derive from the
same outer form and subtract only their interior voids (shared-outline principle).

Usage: outline_loft.py ref.stl y1 y2 ... > outline.scad
Pick stations ~1.5mm apart in slowly-varying spans, denser at transitions/tips.
"""
import sys
import numpy as np, trimesh
from scipy.spatial import ConvexHull

ref, ys = sys.argv[1], [float(v) for v in sys.argv[2:]]
m = trimesh.load(ref, force="mesh")
print(f"// GENERATED by outline_loft.py from {ref}. Shared measured outer form:")
print("// loft (ruled hulls) between X-Z convex section outlines of the reference")
print("// tessellation. Edit by re-running the generator with adjusted stations.")
print("profiles = [")
for y in ys:
    s = m.section(plane_origin=[0, y, 0], plane_normal=[0, 1, 0])
    if s is None:
        print(f"// y={y}: no section")
        continue
    pts = s.vertices[:, [0, 2]]
    hp = pts[ConvexHull(pts).vertices]  # CCW ordered
    row = ",".join(f"[{x:.3f},{z:.3f}]" for x, z in hp)
    print(f" [{y:.2f}, [{row}]],")
print("];")
print("""
module station_slab(p) translate([0, p[0], 0]) rotate([90, 0, 0])
  linear_extrude(0.02) polygon(p[1]);
module outer_body()
  for (i = [0:len(profiles) - 2]) hull() {
    station_slab(profiles[i]); station_slab(profiles[i + 1]);
  }
""")
